excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - MarvelHeroesTradeTests
  - MarvelHeroesUITests

disabled_rules: # rule identifiers to exclude from running
  - nesting

line_length: 160

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
    - lhs
    - rhs
    - ts