# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# ignore all warnings from all dependencies
inhibit_all_warnings!

target 'MarvelHeroes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelHeroes
  pod 'SwiftLint', '~> 0.27'
  
  target 'MarvelHeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelHeroesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
